---
-  
   hosts: webserver
   gather_facts: no
   become: yes

   tasks:
   - name: install httpd
     yum:
       name: httpd
       state: latest
  
   - name: start and enable httpd
     ansible.builtin.service:
       enabled: yes
       name: httpd
       state: restarted

   - name: copy the file to the default server location
     ansible.builtin.copy:
       src: index.html
       dest: /var/www/html/index.html
